### ISSUE TITLE
vbCancel error message

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#878] opened 2022-05-26 08:51 UTC
**Describe the bug**
I try to load a smaller, VB6 written application.
uResult declared as: Dim uResult   As VbMsgBoxResult

Works well in VB6 but gives error message (please see the attached screenshot!) in TWB.

**Desktop (please complete the following information):**
 - OS: Windows7 64bit
 - twinBASIC compiler version: Beta 50

**Additional context**

![Image333](https://user-images.githubusercontent.com/94013032/170451644-a8a7a34f-d96d-48fb-b2a9-0d4a33422659.jpg)

**Comment by Kr00l** [comment] 2022-05-26 08:55
Duplicate of #718

**Closed by Kr00l** 2022-05-26 08:55 UTC
