### ISSUE TITLE
OT perhaps: Settings VSCode

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#334] opened 2021-08-07 07:53 UTC
I am little bit worried, what this means. Anyone has a suggestion?
![grafik](https://user-images.githubusercontent.com/41230018/128593123-8dc75eab-9efa-458d-b43e-ae5ff562e67a.png)

**Comment by WaynePhillipsEA** [comment] 2021-08-07 08:06
Duplicate of #89.  It's not a problem on your machine, just a problem of tB.  I'll hopefully look at it very soon.

**Closed by WaynePhillipsEA** 2021-08-07 08:06 UTC

**Comment by uwbwsvd** [comment] 2021-08-07 08:51
That reassures me. Also because I wasn't sure whether I should post this.

**Comment by WaynePhillipsEA** [comment] 2021-08-07 09:08
If in doubt, then please post.  I won't bite😜

**Comment by WaynePhillipsEA** [comment] 2021-08-07 10:39
Should be fixed in v0.10.3988, see comment https://github.com/WaynePhillipsEA/twinbasic/issues/89#issuecomment-894637324
