### ISSUE TITLE
SSTAB_Click produces pollution.

### ISSUE THREAD

**Issue by camomille22003** [WaynePhillipsEA/twinbasic#919] opened 2022-06-18 05:34 UTC
Thank you for this huge progress on this control.

Details that don't work:

1) In design mode, you can't click on tabs to change pages, probably because of the lack of "Index Property".

2) From launch, 4 unsolicited SSTAB_Click calls (without any click)

![Image3](https://user-images.githubusercontent.com/33807881/174424387-c1eef81b-6772-4338-a488-6df53abce910.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 56

**Comment by WaynePhillipsEA** [comment] 2022-06-18 05:53
You're welcome.   I cannot reproduce the click event pollution that you describe.  Please try creating a new form with just the SSTab and the click event to test it.

Clicking on the tabs in design mode works fine here.   You first have to select the control, and then click on a tab and it should update.

**Comment by camomille22003** [comment] 2022-06-18 08:43
1) In design mode with creating a new form and just an SSTAB, the pages still don't change (sometimes it changes but it opens any page).
Before I lose my head, I enclose my test:

[essaiTab.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8933250/essaiTab.zip)


2) Indeed the creation of a new form and just an SSTAB confirms the proper functioning of the call to SSTAB_Click.
To continue my tests, I will isolate this pollution.

**Comment by camomille22003** [comment] 2022-06-20 14:53
Version 58 testing

In design mode:
We still cannot increment the tab by clicking but only by "current tab ActiveX properties"
The top of the tab moves well, but remains on the first page (0), so all the controls placed remain visible regardless of the selected tab.

In use mode:
Clicking on the top of the tab works perfectly, but the first page (0) remains fixed and displays all the controls placed on each tab.

result in Tb:
![Image1](https://user-images.githubusercontent.com/33807881/174628483-079cb8d6-7dd5-4c60-9611-93230e6e0476.jpg)


Result in VB6:
![Image2](https://user-images.githubusercontent.com/33807881/174628534-51aa37c4-633a-4c8d-9667-d339165aab1b.jpg)

**Comment by WaynePhillipsEA** [comment] 2022-06-20 15:02
We do not support frames/containers yet.  That is a known issue from the big IDE thread.   Controls are currently not added to the frame container, but just to the form.

The tabs themselves move correctly in design mode for me on several machines.  Here is a gif:

![tbSSTab_1](https://user-images.githubusercontent.com/25738109/174630609-eec35fa4-1e76-417f-a7f6-ded48005c115.gif)

**Comment by WaynePhillipsEA** [comment] 2022-06-20 15:05
@camomille22003   are you using the Zoom feature of the form designer?   I just noticed that when the zoom is not 100%, the clicking does not work correctly.

**Comment by camomille22003** [comment] 2022-06-20 15:56
Here is the short video

![Animation](https://user-images.githubusercontent.com/33807881/174640003-1bfdcaf4-6635-4307-bb7b-ac96d518bc7f.gif)

**Comment by WaynePhillipsEA** [comment] 2022-06-20 16:46
I suspect it's related to monitor DPI, but I haven't yet reproduced at different DPIs on my machine here

**Comment by Kr00l** [comment] 2022-06-20 17:05
Can it be due to different scaling units? For example pixels vs twips.
This was just a guess out of the blue.

**Comment by bclothier** [comment] 2022-06-20 17:21
#775 may be relevant.

**Comment by camomille22003** [comment] 2022-06-20 17:50
Test on another computer, same program above.
The first was a 15.4" 1366x768 laptop
The second below is a 17" 1920x1080 laptop

![Animation2](https://user-images.githubusercontent.com/33807881/174655557-8c76411d-85c3-4840-8df1-99c324cb168d.gif)

**Comment by camomille22003** [comment] 2022-06-21 05:32
For information :
the 15.4" scale level is 125%
and the 17" by 100%
the 2 under W10

**Comment by WaynePhillipsEA** [comment] 2022-06-21 05:54
I've tested on three different laptops now (W7 / W10 / W11), all with different resolutions and DPI scales.  I simply cannot reproduce this problem at present.

Can anyone else here reproduce the issue?

**Comment by camomille22003** [comment] 2022-06-21 06:04
for testers :
[essaiTab.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8946211/essaiTab.zip)

**Comment by camomille22003** [comment] 2022-06-21 07:57
The solution to solve my problem is to set the zoom to 75%

![Animation4](https://user-images.githubusercontent.com/33807881/174747184-84aaa70c-c3a7-4db3-a78b-a45d3a6ff8b1.gif)

**Comment by WaynePhillipsEA** [comment] 2022-06-21 08:17
That won't work on the next release, because I have fixed the Zoom to work correctly on my machines.

**Comment by WaynePhillipsEA** [comment] 2022-06-21 12:08
@camomille22003 ... are you using Remote Desktop?

**Comment by camomille22003** [comment] 2022-06-21 12:14
> @camomille22003... utilisez-vous le Bureau à distance ?

no, never used

**Comment by camomille22003** [comment] 2022-06-21 12:30
> @camomille22003 ... are you using Remote Desktop?

Do you want me to enable remote desktop ?

**Comment by WaynePhillipsEA** [comment] 2022-06-21 12:37
No, @wqweto mentioned the RD issue above which seemed like it might explain the behaviour you're seeing.  But since you're not in an RDP session, then it can't be that.

**Comment by mburns08109** [comment] 2022-06-21 13:46
For me: I got this in the IDE dbug console:
PROJECT ERROR: unable to load type library reference 'Microsoft Tabbed Dialog Control 6.0 (SP6)'
Executing '[Form1].Show'...
[DEBUGGER] FIXED HIDDEN WINDOW (HWND 1247534)
(runtime error -2147467259: Unspecified error)

which, on F5, led to: a popup msgbox with "9402" (vbokonly)
(just in case you want to add error handling for this case)

**Comment by WaynePhillipsEA** [comment] 2022-06-21 13:50
Unfortunately you won't be able to test it unless you have VB6 installed, or have installed SSTAB through other means.   I'm aware of the 9402 etc messages, they are to be worked on later this week.

**Comment by mburns08109** [comment] 2022-06-21 13:57
OK - from that starting point, I installed the mxcomctl.ocx.
Now, I get: "failed to deserialize JSON" in the activex properties.
and
![image](https://user-images.githubusercontent.com/11444628/174817484-1c35192d-5824-443e-a3e6-4a6ab1f4f953.png)

**Comment by WaynePhillipsEA** [comment] 2022-06-21 14:01
SSTAB is separate from the common controls packs.  You'd need the OCX file plus the .reg file from the VB CDROM in order to install it.

**Comment by bclothier** [comment] 2022-06-21 15:02
Just an idea.... Maybe try and make a video of you clicking either tab 1 and tab 2 but on different locations of the tab. For example, first click on the just inside the very left edge of the tab, then try again on very right edge. Repeat for the top/bottom, then for each 4 corners.

If it's really a scaling problem, then I would expect the clicking to behave differently depending on the location of the click within the tab's client area and thus may give a clue where the problem is.

**Comment by bclothier** [comment] 2022-06-21 15:15
[Just in case it was missed](https://github.com/WaynePhillipsEA/twinbasic/issues/919#issuecomment-1160686940):

> https://github.com/WaynePhillipsEA/twinbasic/issues/775 may be relevant (thinking that if multiple monitors are involved, taking the metrics from the wrong monitor may mess thing up).

**Comment by WaynePhillipsEA** [comment] 2022-06-21 15:15
@camomille22003 are multiple monitors involved?

**Comment by camomille22003** [comment] 2022-06-21 15:21
> @bclothier it's definitely a scaling problem, somewhere between the webpage DOM event and the translation into WM_LMOUSEDOWN messages.
> 
> @camomille22003 could you ensure you've got the latest WebView2 runtime installed? (Evergreen version)

My WebView2 Runtime version is 101.0.1210.53

**Comment by camomille22003** [comment] 2022-06-21 15:25
> Just an idea.... Maybe try and make a video of you clicking either tab 1 and tab 2 but on different locations of the tab. For example, first click on the just inside the very left edge of the tab, then try again on very right edge. Repeat for the top/bottom, then for each 4 corners.
> 
> If it's really a scaling problem, then I would expect the clicking to behave differently depending on the location of the click within the tab's client area and thus may give a clue where the problem is.

I have already tried in every nook and cranny of the tab, but nothing works.
For the moment, it does not matter since only page 0 is displayed.
I will review the problem when we have access to the other pages.

**Comment by camomille22003** [comment] 2022-06-21 15:33
On my 17"  WebView2 Runtime version is 102.0.1245.44 But there is the same problem

**Comment by EduardoVB** [comment] 2022-06-21 16:03
Hello, the problem seems to be that the mouse coordinates horizontally (just horizontally, vertical ones are no affected) are somewhat "scaled". 
To select a tab I need to click all at left. To select the third tab I need to click at the end of the first tab (inside it).

Windows 11, tB 59, screen: 1 monitor at 1920x1080 125% DPI

https://user-images.githubusercontent.com/42319299/174844852-aeec26e6-24f1-43ef-8ae5-4a566d9c8a04.mp4

**Comment by EduardoVB** [comment] 2022-06-21 16:06
> could you ensure you've got the latest WebView2 runtime installed? (Evergreen version)

How do you check that (I never installed any Webview).

**Comment by bclothier** [comment] 2022-06-21 16:12
> How do you check that? (I never installed any Webview).

Via Add & Remove Programs:
![image](https://user-images.githubusercontent.com/2367644/174847453-3a20fcfb-0c15-4609-92a0-129fbbd22bb2.png)

**Comment by EduardoVB** [comment] 2022-06-21 16:17
> The x-scaling there seems very prominent, about 3x what it should be.

Exactly, about 3x (at least here).
And horizontally it is OK, 1x.

**Comment by camomille22003** [comment] 2022-06-21 16:21
What is reproducible:
to open tab 0 click on the far left of tab 0
to open tab 1 click on the far left of tab 1
to open tab 3 click on the far left of tab 2
for tab 2 ????

**Comment by camomille22003** [comment] 2022-06-21 16:49
Problem solved, it was enough to inform TabMaxWidth

![Image1](https://user-images.githubusercontent.com/33807881/174854695-5bfb013d-fe4f-40fb-a015-6db9c66d0028.jpg)

**Comment by WaynePhillipsEA** [comment] 2022-06-21 18:29
To be clear, TabMaxWidth saves fine in both versions of the DLL here.   But I can only reproduce the x-coordinate problem in 6.1.98.39.

**Comment by EduardoVB** [comment] 2022-06-21 20:37
TabMaxWidth has 0 here and I never changed it.
I have TABCTL32.OCX version 6.1.97.82 (and has the problem).

I'm experiencing the same problem with my SSTab replacement [SStabEx](https://www.vbforums.com/showthread.php?858735-(VB6)-SSTabEx-SSTab-replacement-Themed-and-with-new-features), but not exactly with the same wrong scale. In this case, placing a SSTabEx control of the same size and same tabs, and same tab size of the SSTab test, selecting the third tab is done by clicking at the start of the second tab and not at the end of the first one.

Video:

https://user-images.githubusercontent.com/42319299/174892654-c2c1d952-13c6-437f-a992-b237300f52fe.mp4

**Comment by WaynePhillipsEA** [comment] 2022-06-22 03:27
Bug fixed; will be available in next release later today.   Thanks all!

**Comment by WaynePhillipsEA** [comment] 2022-06-22 05:56
Fixed in BETA 60.  Thanks!

**Closed by WaynePhillipsEA** 2022-06-22 05:56 UTC
Labels: more-info-needed

**Comment by EduardoVB** [comment] 2022-06-22 12:26
The underlying issue does not seem to be fixed.
