### ISSUE TITLE
ActiveX DLL different to VB

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#536] opened 2021-12-07 14:47 UTC
**Describe the bug**
An ActiveX-DLL compiled in tB is different from the VB6 generated DLL.
Also the tB DLL doesn't work.

**To Reproduce**
Only to reproduce in my environment.

**Expected behavior**
DLL should work.

**Screenshots**
This is from the test app:
![image](https://user-images.githubusercontent.com/88059532/145050518-10d73233-81bc-42ab-8c1f-60817fddb5a0.png)
![image](https://user-images.githubusercontent.com/88059532/145050417-e8d81209-87a1-4e23-b0bd-2f9e3a228350.png)

The test app runs fine with the VB6 generated DLL.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.23

**Additional context**
Please give me instructions what I should provide in order to track down the issue.

---

If it is of any use, I could offer a remote connection to this development machine.
Perhaps the most efficient method to explore and find the causes.

**Comment by KarlSevenSeven** [comment] 2021-12-11 08:49
Will test later today, perhaps it is fixed now.
https://github.com/WaynePhillipsEA/twinbasic/issues/552#issue-1077074178

**Comment by KarlSevenSeven** [comment] 2021-12-11 19:44
No it's not good.
Same error message when trying to use the tB generated DLL.
The object browser still show differences:
![image](https://user-images.githubusercontent.com/88059532/145689533-b24c3293-1791-4dc6-8281-c33f87502c0c.png)

---

Wayne, please tell me what to test and try and to report back.
I'm not able to shrink the DLL source to simplify the issue.
It only works as a whole.

**Comment by WaynePhillipsEA** [comment] 2021-12-11 20:04
Sorry, haven't had chance to look at this yet.  I'm guessing the extra members in the object browser are likely due to Friend members being interpreted as Public in tB at the moment (known issue), but that in itself shouldn't cause a problem.

At a guess from your first screenshot of the compilation error, I'd say it's probably the OLE_COLOR data type.  It might be coming through as Long in the tB type library?  You should be able to check the signature of that method in the object browser to see what's wrong.  If not, I'll have a look at this for you in the morning.

**Comment by KarlSevenSeven** [comment] 2021-12-11 20:40
Aha, the color.
In the test app I replaced all OLE_COLOR with long.
Works so far, but...

EvtProcess is not available.
'Class not registered.'
```
Private Sub Form_Load()
    Dim DefFile As String
    Dim DefFileDir As String
    
    Set Process = New EvtProcess
```
The class is in the DLL source.
![image](https://user-images.githubusercontent.com/88059532/145690976-ba1ce9ca-0273-426f-8196-3f8647bc2316.png)

**Comment by WaynePhillipsEA** [comment] 2021-12-11 20:55
Hmmm first check that you're compiling the DLL to the correct bitness (presumably win32).  

After building the DLL did you see a message in the debug console saying that DllRegisterServer was successful?  (also make sure you're not running VS code with the Run As Administrator option)

Finally, just to be sure, remove the reference to the library in your project, and then add it again just to make sure VBx hasn't cached the previous builds CLSID/IIDs.

Other than that, I can look at it in the morning for you.

**Comment by WaynePhillipsEA** [comment] 2021-12-12 06:10
Just checked here -> built win32 DLL with tB -> created an Access project (32-bit) -> enabled CPP reference in VBA -> `New EvtProcess` worked without error.

**Comment by KarlSevenSeven** [comment] 2021-12-13 11:07
`first check that you're compiling the DLL to the correct bitness (presumably win32)`
etc.

All double and triple checked.

I stripped down the VB6 test app to a minimum, it shows the error:
[AX_Problem_1.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7703216/AX_Problem_1.zip)

**Comment by WaynePhillipsEA** [comment] 2021-12-13 11:23
Your VB6 project opened fine here, and stepping through the Form_Load code worked.

Are you running the VB6 IDE with the Run As Administrator option?   If so, you'll need to run VS Code with the same, otherwise the DLL registration won't be effective.

**Comment by KarlSevenSeven** [comment] 2021-12-13 13:34
Ok.
But I don't understand:

On build, running VS/tB as a normal user registers the DLL (to where?).
Using the DLL as an admin doesn't work.
That's what I experienced.

So I start my test app as a normal user.
Then, as you said, it works.
Solved so far.

Usually I run VB6 using admin rights.
To be able to use the DLL, I registered the DLL with admin rights (regsvr32 ...).
'Successfully registered'.
VB6 with admin rights doesn't eat the DLL.

I'm confused now - shouldn't the DLL work when registered with admin rights?

---

Running VS/tB with admin rights doesn't register the DLL correctly.

[UNREGISTER] type-library deregistration FAILED.   DllUnregisterServer() returned TYPE_E_REGISTRYACCESS (launch VS Code with 'Run As Administrator' option)
[BUILD] failed

Manually deleting the DLL before build helps.

In the VS/tB settings I now have set 'Register DLLs to HKEY_LOCAL_MACHINE'.

---

Besides the confusion, the DLL is now usable.
There are still errors, I'll open another issue for that.

**Comment by bclothier** [comment] 2021-12-13 14:05
> Manually deleting the DLL before build helps.

Just saw this message which seems similar to #561 that I just opened.

> I'm confused now - shouldn't the DLL work when registered with admin rights?

I'm not clear from your description whether this was even when it's set to use HKLM, not HKCU which it defaults to. Windows has a security rule that prevents admins from using HKCU registration which is why it will fail for anything that's been registered in HKCU but is run as an administrator. To run it as an administrator, it must use HKLM. You indicated that you have set it to use HKLM, which I expect will fix the issue. Or am I missing something?

**Comment by KarlSevenSeven** [comment] 2021-12-13 14:09
You got me right.

**Comment by KarlSevenSeven** [comment] 2021-12-15 10:11
OLE_COLOR / Long

In the test app I changed OLE_COLOR to Long in order to work.

OLE_COLOR should work as well.

**Comment by WaynePhillipsEA** [comment] 2021-12-15 16:59
> OLE_COLOR / Long
> 
> In the test app I changed OLE_COLOR to Long in order to work.
> 
> OLE_COLOR should work as well.

That is now fixed, as of v0.13.37, thanks.

**Comment by KarlSevenSeven** [comment] 2021-12-20 15:15
I gave 0.13.48 a try.
Compiled the ActiveX source with VS admin rights, so the DLL is registered.

In the VB6 test app:

`Private Sub Process_ListGenerated(ByRef List As GeoList)`
```
Compile error:
Procedure declaration does not match description of event or procedure having the same name
```

This is new, it wasn't in 0.13.25.

Test app see here:
https://github.com/WaynePhillipsEA/twinbasic/issues/536#issuecomment-992351579

**Comment by WaynePhillipsEA** [comment] 2021-12-20 15:28
Hmmm... yes GeoList is coming through the type library as Object (IDispatch) now.  I'll get that fixed.

**Comment by WaynePhillipsEA** [comment] 2021-12-20 15:43
Fixed in v0.13.49, should be available in the marketplace in a few minutes.    Note that now that OLE_COLOR gets outputted correctly, you'll probably need to change those color Longs in the VB6 consumer to OLE_COLOR so that the signatures match.

**Comment by KarlSevenSeven** [comment] 2021-12-21 09:02
OLE_COLOR is not right in every place.
Look in the object browser 'RampingColors()'.

tB compiled DLL:
```
Sub DoGeneration(CSVStr As String, Offset As Double, Offsets, OffsetsCount As Long, Stepover As Double, GT As GenerationType, RampType As RampingType, RampsDepths As String, RampAngle As Double, **RampingColors() As Long**, MillingCCW As Boolean, DoFinalPath As Boolean, ZigzagAngle As Double, ZigzagRoundFactor As Double, StartPoint As StartPointType, Process As EvtProcess, Progress As EvtProgress)
    Member of CPP.Controller

```
VB6 compiled DLL:
```
Sub DoGeneration(CSVStr As String, Offset As Double, Offsets, OffsetsCount As Long, Stepover As Double, GT As GenerationType, RampType As RampingType, RampsDepths As String, RampAngle As Double, **RampingColors() As OLE_COLOR**, MillingCCW As Boolean, DoFinalPath As Boolean, ZigzagAngle As Double, ZigzagRoundFactor As Double, StartPoint As StartPointType, Process As EvtProcess, Progress As EvtProgress)
    Member of CP_CPP24.Controller
```

**Comment by WaynePhillipsEA** [comment] 2021-12-21 09:15
Ah ok, arrays with typedefs still coming through as the resolved types.  I'll get that fixed, thanks.

**Comment by WaynePhillipsEA** [comment] 2021-12-21 12:37
Fixed in v0.13.51, thanks

**Comment by KarlSevenSeven** [comment] 2021-12-21 13:13
Works, thanks.
FYI:
DLL still gives no result.
As said, I'll wait.

**Comment by KarlSevenSeven** [comment] 2022-02-16 13:19
0.14.20

I tried again, my source compiles fine.
But the ActiveX DLL still gives no results.

I'm not able to find the error in tB.

Wayne, do you have a fresh idea how to debug?
If not, I can wait.

**Comment by KarlSevenSeven** [comment] 2022-02-16 13:20
And why is this issue closed?
The problem is still there...

**Comment by wqweto** [comment] 2022-02-16 13:34
You **have** to provide a minimal test project that can reproduce the problem together with expected result.

Keep in mind that Wayne is a human, there are humans on the other side of this communication channel.

Asking passive-aggressive questions is the fastest way to demotivate anyone.

**Comment by WaynePhillipsEA** [comment] 2022-02-16 14:57
Indeed, as @wqweto says, this really needs a minimal example to reproduce the problem.  I can appreciate that it's difficult to identify the problem here at the moment.  I'll re-open as I agree this shouldn't have been closed.

**Comment by KarlSevenSeven** [comment] 2022-02-16 20:56
@wqweto 
I apologize when I sounded aggressive, it is not my intention!
Really not.

Regarding the min example:
I tried to make such an example.
There are 3 obstacles:
1. The source is complex and large.
2. It is closed source.
3. The test app requires additional components.

I could strip down the test app to something minimal.
Not the source of the ActiveX DLL.

I'm very willing to find the cause myself, but I don't know how in tB.
Therefore I asked for a fresh idea on how to debug.

"I can wait" is not a joke and not meant passive aggressive.
It is the truth.

---

Also I very know that it's crucial to be able to retrace an error in order to fix it.
I have a test app which allows this.
It's too much effort for Wayne to fiddle with it.

**Comment by mansellan** [comment] 2022-02-16 21:32
Bear in mind that this tracker is (by necessity) in English - which is by no means everyone's first language. It's understandable that there are misunderstandings. Try not to jump to the conclusion that passive aggression, sarcasm or other negativity is intended by a contributer, unless the evidence is overwhelming.

**Comment by KarlSevenSeven** [comment] 2022-05-21 07:56
I suggest to close this.
There were many important fixes in the meantime.

**Comment by WaynePhillipsEA** [comment] 2022-05-21 08:04
Yes, I agree.  We're getting closer with your file now, and have more refined issues opened, so we'll close this.  Thanks

**Closed by WaynePhillipsEA** 2022-05-21 08:04 UTC
