### ISSUE TITLE
Project cannot be saved after switching from 32 to 64 bit mode.

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#729] opened 2022-02-11 09:26 UTC
**Describe the bug**
I have a project that uses Declares.  This works fine in twinBasic 32 bit but I can't test it in VBA as that environment is 64 bit.  Switching the VSCode twinBasic environment to 64 bit and making a few edits leads to an uneditable/unsavable state.  Project attached.
[Enumerable64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8047369/Enumerable64.zip)

This is not urgent or important as the obvious workaround is to do the necessary editing in VBA.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g. 0.14.15]

**Comment by WaynePhillipsEA** [comment] 2022-02-11 09:49
Looks to be crashing in both bitnesses due to a bug in AddressOf.   I'll push out a fix for this shortly as I would like to see if #723 is fixed anyway.

**Comment by WaynePhillipsEA** [comment] 2022-02-11 09:54
That's fixed in v0.14.16.  It was caused by bad syntax on the lines using AddressOf, now remedied.  Cheers.

**Closed by WaynePhillipsEA** 2022-02-11 09:54 UTC
