### ISSUE TITLE
Support: Where does Debug.Print log to in a compiled dll?

### ISSUE THREAD

**Issue by Greedquest** [WaynePhillipsEA/twinbasic#465] opened 2021-10-09 10:36 UTC
I have compiled an ActiveX dll. I would love to have some debug info logged to the VBA immediate window - is this possible? Right now I just litter tB code with MsgBox which works decently but I prefer Debug.Print syntax and of course I don't have to press OK constantly to go through the messages.

**Comment by WaynePhillipsEA** [comment] 2021-10-16 04:39
You'd need to implement this yourself by passing a VBA class instance over to your tB code that exposes a method, say DebugPrint.  In tB you'd store that object in a global variable.   The problem though, is that when your VBA project gets reset during the course of normal VBA programming, you'll need tB to drop that object instance.  

To fix that, you'll need to have your VBA project keep hold of a tB object in a VBA global variable that will then release the tB global variable in its Class_Terminate event.  That way, when the VBA project is reset/ended, the tB class object will be freed automatically by VBA and that triggers its Class_Terminate event which you will then in turn release the VBA class object.  Hope that makes sense.

**Comment by WaynePhillipsEA** [comment] 2021-10-16 07:44
Yes, it should do.  VBx mutes everything internally during an abrupt End, but still has to release its external COM references.

**Comment by madeinaus** [comment] 2021-10-17 10:56
Windows has a debug.print API, which you can observe with a utility that displays debug messages. It's trivial to add it to a program, and would be easy to add as a feature of TB. That assumes TB would only build DLL's for Windows. Is that a fair assumption?

**Comment by LeslieMurphy** [comment] 2021-10-31 21:07
Where does debug.print go in a compiled EXE?  I ran a test from command line as well as within VS Code and do not see the console messages

**Comment by WaynePhillipsEA** [comment] 2021-10-31 21:21
At the moment, Debug.Print does not get compiled into EXEs.  This is the same behaviour as VB6.

**Comment by LeslieMurphy** [comment] 2021-10-31 21:24
Thanks! Is there some way I can see the log messages in VS Code for debugging?  Is there an easy way to write to the console?

**Comment by WaynePhillipsEA** [comment] 2021-11-01 06:37
@LeslieMurphy for writing to the console, please see the code provided by @bclothier in https://github.com/WaynePhillipsEA/twinbasic/issues/47

When you're debugging within VS Code, you'll see the Debug.Print message in the Debug Console.   Note that if you use the 'Build' button, that generates the EXE and runs it, but does not debug it.  To debug the code, you should run the Main() procedure from the Debug Console (or press F5 when the caret is inside the Main procedure)

**Comment by LeslieMurphy** [comment] 2021-11-01 11:44
I could not figure out how to start the Debugger - the icons at the top have a stop button but not a play.  Using F5 I can now debug, and indeed see the output from debug.print.  I don't need to view the debug.print from the EXE at this point though it would be "nice to have".

**Comment by WaynePhillipsEA** [comment] 2021-11-01 12:01
@LeslieMurphy   Thanks for the feedback, we'll consider what to do to improve on that.  

The problem is that VS Code sees twinBASIC as **_always_** debugging, since our debugger is constantly alive to accommodate the always-live Debug Console (much like how the immediate window works in VBx).  

Since VS code sees us as always debugging, it always shows it's pause icon, unless you're stepping through code... in which case it shows the play icon for 'continue'.   You may have noticed that there's a 'Run' icon that we added at the end of the group of icons , which is an image of person running, and that does the same job as F5 in lack of a play button.    We didn't want to use a play icon for it, as it would be confusing to have two play buttons given the built-in one that shows whilst stepping through code.

Ideally, VS Code would just allow us to remove the built-in play/pause button and then we could provide our own more suitable version, but at the moment it doesn't allow for that.   I'm pretty sure Theia (#458) would, if we decide to go down that route in the future, or it may require us to ask the VS Code team to accommodate our needs on this.

**Comment by LeslieMurphy** [comment] 2021-11-01 12:15
Aha so that is what that run icon does!  I thought it was a visual annotation associated with the file name of the source code tab!

FYI - My filename is HelloWorld.twin and in VS Code the tab showed up as d.twin.   I see now that it I resize the VS Code window I can completely obscure the file name tab(s) with the twinbasic run menu.  Should I report a bug for this?  VS Code 1.61.2, Electron 13.5.1.

IMHO I would use a play arrow for the icon.  Perhaps a solid Green one.  The hover text tooltip can explain what it does.  When the debug session is active you could disable the button.

**Comment by WaynePhillipsEA** [comment] 2021-11-01 12:31
> I see now that it I resize the VS Code window I can completely obscure the file name tab(s) with the **_twinbasic run menu_**

Do you mean the floating toolbar?  If so, that's a pain point with VS Code, in that it doesn't allow for proper toolbars, so instead we've got the floating toolbar that I admit is quite annoying.  You can move it around, but ultimately it always ends up obscuring something.

> IMHO I would use a play arrow for the icon. Perhaps a solid Green one. The hover text tooltip can explain what it does. When the debug session is active you could disable the button.

Yes that might just work, and if we were to arrange the new icon to be put at the beginning of the group, before the current pause button, when our play button gets disabled (during stepping), the 'continue' built-in play button will be in its place.  We'll look into that, thanks.

**Comment by LeslieMurphy** [comment] 2021-11-01 12:50
I see now that I can use the leftmost icon to move the floating toolbar.  Good to know.

Is this https://github.com/Microsoft/vscode/issues/52490 issue relevant?  It seems like the VSCode team tried to address this.

**Comment by WaynePhillipsEA** [comment] 2021-11-01 13:07
Yes, that issue pretty much covers the problems, but the fix is not great IMO.   The VS Code team made the floating toolbar a little bit more flexible.... but ultimately it's still a floating toolbar that will obscure something.   The docked toolbar doesn't work well for me, as I don't have the Debug and Run activity pane open (ever)... I instead have the Variables / Debug Console etc moved into the pane on the RHS so that I can have my project explorer open on the LHS at the same time as the debug views.

**Comment by bclothier** [comment] 2022-06-16 02:57
Closing the issue as addressed the original question.

**Closed by bclothier** 2022-06-16 02:57 UTC
Labels: question
