### ISSUE TITLE
Position controls on SSTab by programming

### ISSUE THREAD

**Issue by camomille22003** [WaynePhillipsEA/twinbasic#941] opened 2022-06-26 06:19 UTC
All the controls placed on the tabs appear on the zero tab if we try to move them programmatically.
Everything is correct if we just move the controls by their properties

![Animation7](https://user-images.githubusercontent.com/33807881/175802157-45b50432-0d6c-4e2d-a029-c21999f10859.gif)

![Animation8](https://user-images.githubusercontent.com/33807881/175802161-0a6cd09f-b746-448c-9ac4-7200b6652778.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 61

**Comment by EduardoVB** [comment] 2022-06-26 18:49
This is "normal" for SSTab, it happens also in VB6.
Or more than normal it is a known defect or limitation.

The reason was explained by @dmrvb in [#939](https://github.com/WaynePhillipsEA/twinbasic/discussions/939#discussioncomment-3023130) (in form of a question):

> Is this just a known limitation of the SStab? you can locate controls from code as long as the tab is visible, but Not if another tab is visible. The SStab has all controls visible but moves the ones from inactive tabs to a position out of range of the screen (left=-30000 or something like that) so if you set left its brings them back visible. 

That's the reason: the controls that are not in the current tab are shift to the left -75000 twips.
If you put them to 0 or small values of Left, then they'll appear in the current tab.

That was partially fixed in the [SSTab replacement](https://github.com/EduardoVB/SSTabEx/) SSTabEx (you can download the OCX file from [here](https://github.com/EduardoVB/SSTabEx/raw/main/control-bin/TabExT01.ocx)) by subclassing the contained controls, but only fixes the issue for controls that are windows (that have the hWnd property), not for controls that are windowless (for example Labels).

For those I made a new property [ContainedControlLeft](https://htmlpreview.github.io/?https://github.com/EduardoVB/SSTabEx/blob/main/docs/tabexctl_reference.html#ilink10). This work for all controls, regardless they are windows or windowless.

There is also a new event and new properties that are intended to ease the control positioning in tabs:

[TabBodyResize](https://htmlpreview.github.io/?https://github.com/EduardoVB/SSTabEx/blob/main/docs/tabexctl_reference.html#ilink94).

Anyway, the best advice is to put all the controls of each tab into a container (like a PictureBox). That's also valid for the SSTab (and with more reasons).
tB still don't have PictureBoxes or Frames that can act as containers, but that's the advice for when these things become available.

**Comment by WaynePhillipsEA** [comment] 2022-06-26 20:03
Just a minor note; the built in Frame does work as a container in the latest releases.

**Comment by camomille22003** [comment] 2022-06-27 07:15
My goal is not to rewrite my 2800 line program with new controls, but to help with this program to verify 100% compatibility between Tb and Vb6. Changing SSTab to SSTabEx is cheating.

**Comment by wqweto** [comment] 2022-06-27 07:53
If SSTab is working in VB6 then it must be working in TB regarding position controls at run-time.

@camomille22003 Can you cobble up a sample repro w/ SSTab (less than 2800 LOC) which works in VB6 but the expected behavior fails in TB?

**Comment by camomille22003** [comment] 2022-06-27 09:15
It's very complicated because on version 62 Start/Stop does not work (only Preview) but here is the result:
Prg Tb :
[TestSSTabTb.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8990403/TestSSTabTb.zip)

Tb works normally without moving :
![Animation10](https://user-images.githubusercontent.com/33807881/175904635-75926618-c530-4443-8192-5044172535fd.gif)

Tb works poorly with displacement :
![Animation11](https://user-images.githubusercontent.com/33807881/175904727-e7b0c78b-4a20-4ba6-924e-046de8d44e59.gif)


Prg Vb6 :
[TestSSTabVb6.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8990408/TestSSTabVb6.zip)

Vb6 works normally without the displacement :
![Animation12](https://user-images.githubusercontent.com/33807881/175904828-d2a08eff-1654-40b1-8021-66bf680edf85.gif)

Vb6 works normally with displacement :
![Animation13](https://user-images.githubusercontent.com/33807881/175904940-d415a2b0-3bf8-4952-b942-2d95c6bb6679.gif)

**Comment by WaynePhillipsEA** [comment] 2022-06-28 10:50
Fixed in BETA 63.  Thanks!

**Closed by WaynePhillipsEA** 2022-06-28 10:50 UTC
Labels: bug, confirmed
