### ISSUE TITLE
Can we keep from losing our licenses?

### ISSUE THREAD

**Issue by mburns08109** [WaynePhillipsEA/twinbasic#922] opened 2022-06-19 02:15 UTC
**Is your feature request related to a problem? Please describe.**
I entered my license info back in the early beta days, but after (essentially xcopy-)installing Beta56 into the same folder I've been using all long, I noticed that my "professional" license was replaced with the "Community" license.

I can't say exactly where along the recent weeks of overlaying Beta version after Beta version in the same folder the license went awry, but somehow, it did.

**Describe the solution you'd like**
not losing the licensing once it's been entered - regardless of downloading newer Beta versions and XCOPY-installing them in the same folder.

**Describe alternatives you've considered**
having to re-enter it in after each new beta version?  Ick!

**Additional context**
Example:
Create a folder: C:\TB_IDE
download a beta version .zip file.
extract it and replace files in the C:\TB_IDE folder with the new beta version files/folders
(lather, rinse, repeat for new beta versions)
(insert the secondary steps here necessary to prevent your virus/malware protection from quarantining any of the newly downloaded executable or DLL files.)
...somewhere along the lines, the license info apparently gets stomped.

To be clearer on this, I'm NOT saying that "Beta56 did this". This could well have happened sooner than this - Beta 53, Beta 48, Beta 42 - I don't know when it happened, exactly. I'm saying only that I _noticed it_ after installing Beta56.

**Comment by bclothier** [comment] 2022-06-19 02:27
FWIW, when the IDE was introduced in lieu of VS code extension, we all had to re-enter the license info since it's a different application. Once entered, it should persist. I've been replacing several IDE versions with no issue to the license.

**Comment by mburns08109** [comment] 2022-06-19 02:32
Perhaps it did happen that far back - I simply can't recall/didn't notice until now.

**Comment by bclothier** [comment] 2022-06-19 02:54
Going to close this since it should be working. If you have a reproduction demonstrating how to lose the license between 2 IDE versions, feel to reopen.

**Closed by bclothier** 2022-06-19 02:54 UTC
