### ISSUE TITLE
ActiveX DLL reference must be refreshed after build

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#114] opened 2021-05-04 02:04 UTC
**Describe the bug**
It seems that if there's a VBA project that references a tB ActiveX DLL project and it has been modified, there are additional actions required to get it to run again.

**To Reproduce**
1. Create an ActiveX DLL project. Include a class with a single method. Names or parameters doesn't matter.
2. Build the project. IDE should register the library.
3. Using a favorite VBA host (e.g. Access), create a new document and in its VBA project, add a reference. 
4. In a module, write code that makes use of the tB class from the referenced library. 
5. Compile & run to verify it works correctly.
6. Close the VBA host completely
7. In IDE, edit something (e.g. add a new private variable)
8. Build it again.
9. Re-launch the same VBA host & open the document. Try to run code. You will get an error about unable to create the object.
10. Go to references, remove the tB project. Close the references dialog
11. Re-open references, add it back again.
12. Compile the code.
13. It runs again.

**Expected behavior**
It should not be necessary to do the step 9-13; it should still to work as before without the additional work of removing/re-adding references. I understand that type library may need to be refreshed if the shape did change (e.g. a parameter was added) but normally editing the internal details should not break the existing client code against it. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2300]

**Comment by WaynePhillipsEA** [comment] 2021-05-04 04:52
Couldn't repro.  Did you have the 'Project: Use Project ID for the type library ID' setting ON in the project settings?  With that setting on, this would be expected behaviour.  With that setting OFF (default), this shouldn't be happening.

**Comment by WaynePhillipsEA** [comment] 2021-05-04 06:03
Just to explain WHY you *currently* want the 'Project: Use Project ID for the type library ID' setting OFF:

VBA typically caches the compilations from one session to the next, unless it detects a change in a type library.  When it detects a change, it drops the persisted compilations and recompiles the code at the next run or manually compile.  When detecting changes in a type library for the recompile purposes, it appears to only look at two things... the type library GUID, and the type library major version number.

tB doesn't yet have persisted/cached CLSIDs and IIDs, so they get generated randomly each time you build.  So if we don't trigger a recompile at the VBA site, the cached VBA compiled code will be referencing the old CLSIDs that are no longer valid, and thus fail.

Once tB supports persisted CLSIDs/IIDs, you would only need to trigger a recompile when a signature change occurs in a method, or changing the public members etc..  i.e. when binary compatibility is lost.  But for now, you want that setting OFF.

**Comment by bclothier** [comment] 2021-05-04 07:50
I can confirm that I did have that checked. With some more testing, I see that just compiling is enough to get the VBA code to work again. 

The reason I turned this on is to avoid registry clutter because in my observation, each build generates a new registration without removing the old ones).

**Comment by WaynePhillipsEA** [comment] 2021-05-04 08:18
@bclothier yes, at the moment that is the case.   I'm starting work on getting DllRegisterServer and DllUnregisterServer implemented today, and once that's done, I can have the IDE call DllUnregisterServer on the old build before starting the new build.

**Comment by WaynePhillipsEA** [comment] 2021-05-04 08:20
I'll close this for now, as this is not a bug but expected behaviour with that flag set.

**Closed by WaynePhillipsEA** 2021-05-04 08:20 UTC
