### ISSUE TITLE
oExcel.Application.Visible = True

### ISSUE THREAD

**Issue by JakubHuber** [WaynePhillipsEA/twinbasic#119] opened 2021-05-04 18:51 UTC
Hello,

When I tried to assign Boolean variable to below statement, Visual studio code reports me a problem on line : **oExcel.Application.Visible = True**

Sample code (Need reference to Excel):

        dim oExcel as Excel.Application = new Excel.Application 
        dim oWorkbook as Excel.Workbook
        
        set oWorkbook = oExcel.Workbooks.Open("C:\Users\Jakub\Desktop\Piosenki.xlsx")
        oExcel.Application.Visible = True
        
        oExcel.Quit

Problem message:
too few arguments, expected 2 in call to 'Visible'

I check with documentation and it only need one argument:
https://docs.microsoft.com/en-us/office/vba/api/Excel.Application.Visible

**Comment by WaynePhillipsEA** [comment] 2021-05-04 19:39
Hi @JakubHuber.  Thanks for your bug report.   I believe this is a duplicate of #96, and was fixed in 0.9.2136.  We're now on v0.9.2355.

Please ensure you are using the latest update by looking at the Extensions pane in VS Code and checking for updates to the twinBASIC extension.

**Comment by WaynePhillipsEA** [comment] 2021-05-05 07:10
Closing as already fixed.  If this still occurs for you with the latest release, please reopen.  Thanks

**Closed by WaynePhillipsEA** 2021-05-05 07:10 UTC
Labels: already-fixed, duplicate

**Comment by JakubHuber** [comment] 2021-05-05 20:44
Hello, thank you for help. I fought that extensions reloads automatically. I had version 2.450 but it was not reloaded... Sorry for bother. :)

**Comment by WaynePhillipsEA** [comment] 2021-05-05 20:48
No problem.  I think VS code usually downloads updates automatically, but doesn't activate them until next restart.  Anyway, thanks for confirming. 👍

**Comment by wqweto** [comment] 2021-05-06 07:38
> I fought that extensions reloads automatically. 

You can click on the `Reload Required` text in the twinBASIC entry in the Extensions panel to reload it (restarts the IDE but remembers open files).
