### ISSUE TITLE
Support isolation-aware manifest for ActiveX Dlls/Controls

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#870] opened 2022-05-23 11:54 UTC
**Is your feature request related to a problem? Please describe.**
We already have the support in place for embedding a manifest file to control the visual styles of a tB project. However, when the project is an ActiveX DLL, it's the host that determines the styles, so the manifest has no effect in this case. 

**Describe the solution you'd like**
In order to allow controls or forms defined within the DLL to control the visual studio, the DLL needs to be isolation-aware, specifying `ISOLATIONAWARE_MANIFEST_RESOURCE_ID` for its manifest so that the visual styles can be applied to those forms/controls regardless of the host.

**Comment by Kr00l** [comment] 2022-05-23 11:56
Duplicate of #569

**Closed by Kr00l** 2022-05-23 11:56 UTC
Labels: enhancement
