### ISSUE TITLE
Async execution works in IDE, not from VBA

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#864] opened 2022-05-21 15:00 UTC
Live from the bleeding edge. (Blood donations needed, please)

**Describe the bug**
I have set up a PoC demonstrating that it is possible to run asynchronously using only Win32 calls and without excessive hackery. This works well from IDE. However, when running the same from VBIDE, we get the errors:
![image](https://user-images.githubusercontent.com/2367644/169655773-937f6cb3-fbda-4167-8bf9-0a2e37b54b1e.png)

Note that the execution already has continued past the `ExtractAsync` invocation as shown by the yellow highlighting on the later lines.

Several dialogs follow:
9508 (shown in the screenshot above)
9402
9403
9508

This seems to be caused by this line in the [`ProgressFactory.MessagePump` procedure](https://github.com/bclothier/TwinBasicSevenZip/blob/f02054179af9ccf2ec503e4e52a7e7bd0e4e84bf/TwinProject/Sources/UI/ProgressDialog/ProgressFactory.twin#L452):
```
Set SharedThreadData.ProgressView = New ProgressDialog()
```

We get an error 91 about object being not set:
![image](https://user-images.githubusercontent.com/2367644/169656610-cca84079-6de9-4da4-af9b-9072ac101412.png)

Which is kind of strange since we're actually trying to set an object.

**To Reproduce**
1. Take the [`dev` branch](https://github.com/bclothier/TwinBasicSevenZip/tree/dev)
2. Build the project 
3. Add and run a modified version of the testing code in IDE:
```
    Private Sub BasicBigExtractTest()
        Dim af As ArchiveFactory = New ArchiveFactory
        af.ExtractAsync("C:\Path\To\Some\Big\Archive.zip", "C:\Path\To\Some\Big\Archive\")
        Debug.Print "Done executing test"
    End Sub
```
4. Run the test, verify it works correctly.
5. Launch Excel
6. Add reference to the 7-Zip COM library
7. Add new module with the following code:
```
Public Sub Demo()
    Dim f As SevenZipArchive.ArchiveFactory
    Set f = New SevenZipArchive.ArchiveFactory
    f.ExtractAsync "C:\Temp\Temp2.rar", "C:\Temp\Test7z_Rar"
    
    Dim s As Date
    Dim i As Long
    
    s = DateAdd("s", 60, Now())
    Do Until Now >= s
        i = i + 1
        Debug.Print i, "The time now is " & Now
        DoEvents
    Loop
End Sub
```
8. Run the code. The `ExtractAsync` will return immediately as expected and VBA code will continue executing but we get the dialogs as shown at the start of the report.

**Expected behavior**
It should work, preferably without bleeding, please. 😄 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE 45

**Additional context**
No thread safety has been implemented. I should think about putting some thread safety in so I could bleed a little less yes? :smile:

**Comment by WaynePhillipsEA** [comment] 2022-05-22 04:56
I was able to reproduce the 9508/9402 linkage errors which are being caused by the progress form class being marked as Private.  This is fixed in the upcoming release.

However, just so that you are aware;  I was unable to get the `BasicBigExtractTest` to run successfully in the IDE (nor from VBA).  The progress dialog appears, but then the following pops up very quickly;

<img width="253" alt="tbSevenZipError1" src="https://user-images.githubusercontent.com/25738109/169679396-7b817971-159c-4e76-a654-c5c06e2ee7c9.png">

**Comment by WaynePhillipsEA** [comment] 2022-05-22 06:10
The linkage issue should be fixed in BETA 46.  Thanks!

**Closed by WaynePhillipsEA** 2022-05-22 06:10 UTC

**Comment by bclothier** [comment] 2022-05-22 10:02
FYI I can confirm that this fixed the issue and now everything works as expected; the progress & work do run asynchronously while VBA is free to continue doing whatever it wants to do. 

Bizarre that you got the class factory error as I don't see it. Will have to investigate how to reproduce this. Thanks!

**Comment by WaynePhillipsEA** [comment] 2022-05-22 10:11
No worries, let me know if you can't repro and need to test anything.

**Comment by bclothier** [comment] 2022-05-22 10:14
Can you confirm you used the import from folder? When I try that, I get build errors due to missing files. But even so, I was able to run the procedure even with the files missing from the dev branch.

**Comment by WaynePhillipsEA** [comment] 2022-05-22 10:16
Yes I did, and had the same few missing files that I located in the master branch.

**Comment by bclothier** [comment] 2022-05-22 10:53
Reproduced; I can get this if I use `7za.dll` instead of `7z.dll` - the sample code I used was extracting a RAR archive file which requires the `7z.dll` (full 7-zip DLL) rather than either `7za.dll` or `7zxa.dll` DLLs. I will need to add better handling in this area so it's clearer what's going wrong. Thanks for pointing out the issue!
