### ISSUE TITLE
vbNormal error

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#879] opened 2022-05-26 08:53 UTC
I try to load a smaller, VB6 written application.

Works well in VB6 but gives error message (please see the attached screenshot!) in TWB.

Desktop (please complete the following information):

OS: Windows7 64bit
twinBASIC compiler version: Beta 50

Additional context
![Image533](https://user-images.githubusercontent.com/94013032/170454243-e6e802c1-2c2e-49f1-aa9b-51c3ed97dc5c.jpg)

**Comment by Kr00l** [comment] 2022-05-26 08:54
Duplicate of #718

**Closed** 2022-05-26 08:54 UTC
