### ISSUE TITLE
Non-breaking space not understood by tB parser

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#251] opened 2021-06-30 14:05 UTC
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/41230018/123973981-8a29b400-d9bc-11eb-8e95-a02fa881dfae.png)

1. typed
2. copy and paste

 - twinBASIC compiler version [v0.10.3212]

**Comment by WaynePhillipsEA** [comment] 2021-06-30 14:15
I suspect the document got out-of-sync with the compiler.  If you make another minor edit  to the file (e.g. add a new line), does it fix the problem?

 I can reproduce similar effects just by typing too quickly.   I haven't looked into it yet, but it's high on the list to be looked at very soon.

**Comment by uwbwsvd** [comment] 2021-06-30 14:55
Paste:
![grafik](https://user-images.githubusercontent.com/41230018/123982920-ba288580-d9c3-11eb-9e30-bf2679515982.png)
Enter-Key after end of line:
![grafik](https://user-images.githubusercontent.com/41230018/123983121-e8a66080-d9c3-11eb-954f-b4743dbff959.png)

**Comment by uwbwsvd** [comment] 2021-06-30 15:13
Perhaps it helps.
[TwinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6741979/TwinBasic.zip)

**Comment by WaynePhillipsEA** [comment] 2021-06-30 15:18
I'm not seeing the second line in your file...

<img width="258" alt="tb_uwbvws1" src="https://user-images.githubusercontent.com/25738109/123987074-cb22c800-d9be-11eb-8e01-fb6a17b5671f.png">

Did you save it first?

**Comment by uwbwsvd** [comment] 2021-06-30 15:33
Second try:
[TwinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6742137/TwinBasic.zip)

**Comment by WaynePhillipsEA** [comment] 2021-06-30 15:38
The character immediately following 'Print' on the second line is a non-breaking space (ASCII char &HA0) rather than a regular space (ASCII char &H20).   twinBASIC is not understanding that space character, so that needs fixing.  Thanks

**Comment by WaynePhillipsEA** [comment] 2021-06-30 15:41
Actually, VB6 / VBA doesn't accept the non-breaking space either.  If you copy and paste that line into VBx then it also fails on it.

Where did you copy that code from to get the non-breaking space?

**Comment by bclothier** [comment] 2021-06-30 15:44
As a caution, VB* unfortunately accepts 0xHA0 as a legal character for the identifiers, enabling you to write evil code like this:
![image](https://user-images.githubusercontent.com/2367644/123991122-0c4fb380-d990-11eb-9495-b4ca10e25174.png)

I think it's a dumb omission and IMNSHO, we shouldn't allow it as a legal identifier but for backward compatibility... ?

**Comment by WaynePhillipsEA** [comment] 2021-06-30 15:49
@bclothier yes, I remember now seeing some of ThuderFrame's code using it.  Crazy really, but for backwards compatibility we'll stick with it, and later we'll produce warnings for it.

Not sure how @uwbwsvd managed to get that character in his statement though, but as it's not legal in VBx, I'll be closing this one.

**Comment by uwbwsvd** [comment] 2021-06-30 15:54
Original copied from a web-page. Then from inside VS-Code. From the "comment" text
![grafik](https://user-images.githubusercontent.com/41230018/123992650-18f1fd00-d9cc-11eb-8f42-a8f220024ef4.png)

**Comment by camomille22003** [comment] 2021-06-30 15:54
![Image2](https://user-images.githubusercontent.com/33807881/123992731-2a3b0980-d9cc-11eb-9393-4afd76d344e2.jpg)

**Comment by WaynePhillipsEA** [comment] 2021-06-30 16:00
@camomille22003 that comment also has the non-breaking space character in it.  If you copy from the good version, to a comment and back again it does not introduce the non-breaking space.

@uwbwsvd ... I believe the problem is with the original source webpage where you got this from.

**Comment by camomille22003** [comment] 2021-06-30 16:04
Copy / paste commented = underline
Copy / paste uncommented = correct

**Comment by WaynePhillipsEA** [comment] 2021-06-30 16:28
@camomille22003 yes, that's expected since the commented out code includes the bad character.   I'll close this, as I'm convinced the character is not being generated by twinBASIC nor VS Code, but is just an error on the webpage where the code originated.

**Closed by WaynePhillipsEA** 2021-06-30 16:28 UTC
Labels: bug

**Comment by wqweto** [comment] 2021-07-01 06:36
Btw, can TB cleanup non-breaking spaces and other copy/paste-from-HTML introduced "goodies" in the current source line prettifier?

**Comment by WaynePhillipsEA** [comment] 2021-07-01 07:49
@wqweto the problem would be that as @bclothier mentioned earlier, for backwards compatibility we need to allow the non-breaking space in symbols / identifiers.  Therefore we can't have the prettifier do this job, as that happens automatically without user confirmation.   I'd be willing for it be identified as a warning (#208), with a quickfix to fix the problems.  Other than non-breaking spaces, what other things have you encountered?   I'm guessing things like double quotes ("" vs “”)?  If we can put a list together, I'll get on to it.
