### ISSUE TITLE
TB App Object Missing Some VB6 App Object Properties

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#608] opened 2021-12-28 17:34 UTC
**Is your feature request related to a problem? Please describe.**
I tried importing my first command-line only VB6 project to tB ([described in detail here](https://www.vbforums.com/showthread.php?893990-VB6-Web-Site-App-Server&p=5550066&viewfull=1#post5550066)). The main "barrier" was that the tB App object is missing some properties that the VB6 App object has.

**Describe the solution you'd like**
For tB to implement all of the VB6 App Object properties.

**Describe alternatives you've considered**
None.

**Additional context**
The missing App object properties are:

App.Comments
App.CompanyName
App.FileDescription
App.HelpFile
App.LegalCopyright
App.LegalTrademarks
App.LogEvent
App.LogMode
App.LogPath
App.Major
App.Minor
App.NonModalAllowed
App.OleRequestPendingMsgText 
App.OleRequestPendingMsgTitle 
App.OleRequestPendingTimeout 
App.OleServerBusyMsgText 
App.OleServerBusyMsgTitle 
App.OleServerBusyRaiseError 
App.OleServerBusyTimeout 
App.Revision
App.PreviousInstance
App.ProductName
App.RetainedProject
App.Revision
App.StartLogging
App.StartMode
App.TaskVisible
App.Title
App.UnattendedApp

**Comment by bclothier** [comment] 2021-12-28 18:34
FWIW, I would file this under #143 since it's a work-in-progress.

**Comment by mburns08109** [comment] 2021-12-29 02:06
> FWIW, I would file this under #143 since it's a work-in-progress.

I can drink to that.

**Comment by jpbro** [comment] 2021-12-29 02:54
> > FWIW, I would file this under #143 since it's a work-in-progress.
> 
> I can drink to that.

Moi Aussi! Sorry that I missed that issue. I thought I searched for "App Object", but I think I must have searched for "Screen Object" (due to an error in another project that I tried to compile with tB). The Screen object is missing and is not an open issue yet. Can we merge issues here, or should I just close this one as "redundant"?

**Comment by WaynePhillipsEA** [comment] 2021-12-29 07:26
Closed as duplicate of #143.  I'll move the extra info into that issue, thanks!

**Closed by WaynePhillipsEA** 2021-12-29 07:26 UTC
